### ISSUE TITLE
README.md should be more informative

### ISSUE THREAD

**Issue by codelover96** [carolinepacheco/Convert-YOLO-to-PascalVOC#2]
Hey there,
first, i'd like to thank you for creating this repo. It has been really useful to my work.

I have written some tips on how to use this script. You might want to add them to README.md, as it might help others avoid the mistakes I made. 

Usage and tips
1) Make sure you have the dependencies listed on yolo_to_voc.py
2) Update root path(where this script lies) in line 46. `ROOT = '/coco/'`
3) Run with python3
4) Let's say that you have a custom dataset, which is not included in COCO. eg ship. Add its name to `YOLO_CLASSES=()`, FIRST position
5) Remove images that are already in /coco/images, /coco/labels and /coco/outputs.
6) Put all your images at /coco/images folder
7) Put corresponding annotations (.txt files) to /coco/labels
8) run script with `python3 yolo_to_voc.py`

Feel free to ask me anything,
Thanks again!
~codelover96

**Comment by carolinepacheco** [comment]
Hi @codelover96,

Thank you very much for your valuable suggestions. 
I just updated the README.md file. In addition, I modified the the path in the line 46  to ``coco``.
